# Default values for in-cluster-ci.

model:
  name: "Qwen/Qwen2.5-0.5B-Instruct" # Using a much smaller model for default testing without needing a large GPU
  resources:
    limits:
      nvidia.com/gpu: "1"
      memory: "8Gi"
    requests:
      nvidia.com/gpu: "1"
      memory: "8Gi"

pipeline:
  name: "odh-analyzer-pipeline"
  schedule: "0 0 * * *" # Daily at midnight
  namespace: "opendatahub"

setupJob:
  image: "quay.io/opendatahub/kubeflow-pipelines-kfp-sdk:latest" # Base python image with KFP
  backoffLimit: 4