# Default values for in-cluster-ci.

model:
  name: "Qwen/Qwen2.5-0.5B-Instruct"
  resources:
    limits:
      memory: "8Gi"
    requests:
      memory: "8Gi"

pipeline:
  name: "odh-analyzer-pipeline"
  schedule: "0 0 * * *" # Daily at midnight
  namespace: "in-cluster-ci"