apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-source
data:
  collect.py: |-
{{ .Files.Get "pipeline/src/components/collect.py" | indent 4 }}
  analyze.py: |-
{{ .Files.Get "pipeline/src/components/analyze.py" | indent 4 }}
  run_health_check.py: |-
{{ .Files.Get "pipeline/src/components/run_health_check.py" | indent 4 }}
  report.py: |-
{{ .Files.Get "pipeline/src/components/report.py" | indent 4 }}
  pipeline.py: |-
{{ .Files.Get "pipeline/src/pipeline.py" | indent 4 }}
