apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-runtime
spec:
  supportedModelFormats:
    - name: pytorch
      version: "1"
    - name: vllm
      version: "1"
  containers:
    - name: kserve-container
      image: vllm/vllm-openai:v0.4.0
      command:
        - "python3"
        - "-m"
        - "vllm.entrypoints.openai.api_server"
      args:
        - "--model"
        - "{{ .Values.model.name }}" # Use the model name directly, vllm will download it from huggingface if not found locally
        - "--port"
        - "8080"
        - "--served-model-name"
        - "{{ .Values.model.name }}"
        - "--trust-remote-code"
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
      resources:
        {{- toYaml .Values.model.resources | nindent 8 }}
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
