apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-runtime
spec:
  supportedModelFormats:
    - name: pytorch
      version: "1"
    - name: vllm
      version: "1"
  containers:
    - name: kserve-container
      image: ghcr.io/huggingface/text-generation-inference:2.4.0-intel-cpu
      command:
        - "text-generation-launcher"
      args:
        - "--model-id"
        - "{{ .Values.model.name }}"
        - "--port"
        - "8080"
        - "--trust-remote-code"
        - "--max-batch-prefill-tokens"
        - "1024"
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: HUGGINGFACE_HUB_CACHE
          value: /tmp/hf_home
        - name: PORT
          value: "8080"
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
        - name: data
          mountPath: /data
      resources:
        {{- toYaml .Values.model.resources | nindent 8 }}
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
    - name: data
      emptyDir: {}
